### PR TITLE
Use "testanchor.stellar.org"

### PR DESCRIPTION
**Pull request by C0x41lch0x41**
Replace "stellar-anchor-server.herokuapp.com" with "stellar-anchor-server.herokuapp.com

### CODE REVIEW

**Review by JakeUrban — APPROVED** [review]
This project should be moved to stellar/deprecated, but we can update the reference

**Comment by leighmcculloch** [comment]
To move the project to stellar-deprecated an issue needs opening in the ops repo.

**Comment by C0x41lch0x41** [comment]
@JakeUrban can you merge it?

**Comment by JakeUrban** [comment]
@C0x41lch0x41 I don't have the ability to merge either it looks like. Looking at the permissions in [terraform](https://github.com/stellar/terraform/blob/master/github/repos.auto.tfvars.json#L106-L119), it looks like admins are the only ones who can merge.

**Pull request merged**
